### ISSUE TITLE
Issue with vEMdiffuse-a not functioning correctly

### ISSUE THREAD

**Issue by Shogosuga** [Luchixiang/EMDiffuse#3]
Hello. I'm using vEMdiffuse-a, but I'm getting poor inference results. 
Could you please advise on what I should do?

I followed the steps in [training.ipynb](https://github.com/Luchixiang/EMDiffuse/blob/master/example/vEMDiffuse-a/training.ipynb) to train the model, and then used [prediction.ipynb](https://github.com/Luchixiang/EMDiffuse/blob/master/example/vEMDiffuse-a/prediction.ipynb) to obtain inference results.
During inference, I modified ```resume='./experiments/vEMDiffuse-a/best'``` to ```resume='./experiments/train_vEMDiffuse-a_240303_001236/checkpoint/500'``` to use my trained model as described in your notebook.
 However, I couldn't achieve the results shown in your original notebook. 

Could you please advise if there's something wrong with my code?

![download](https://github.com/Luchixiang/EMDiffuse/assets/43239176/cf7e17be-cb59-4f88-9656-1dd01d1182b2)

**Comment by Luchixiang** [comment]
The demo dataset in training.ipynb only consists of 24 layers from MICrONS multi-area volume, which is too small to train a diffusion model.  To improve the performance, you should download more data from the [MICrONS multi-area volume](https://www.microns-explorer.org/) and train the diffusion model for a longer time (about 1000 epochs).

**Comment by Shogosuga** [comment]
Thank you for your quick response!

I want to set the number of epochs, so could you tell me which variable in the [vEMDiffuse-a.json](https://github.com/Luchixiang/EMDiffuse/blob/master/config/vEMDiffuse-a.json) sets the number of epochs?
```["train"]["n_epoch"]``` or ```["train"]["n_iter"]```?

**Comment by Luchixiang** [comment]
Both works for setting the training duration. n_iter controls the number of iteration and n_epoch controls the number of epochs

**Comment by Shogosuga** [comment]
I see.
Your paper states, 'we terminated the training after 1200 epochs'. 
Did you achieve this by simply setting the ['train']['n_epoch'] variable in the config to 1200?

**Comment by Luchixiang** [comment]
yes
