### ISSUE TITLE
Reproduce vEMDiffuse-i on EPFL brain dataset (Supp. Fig.18)

### ISSUE THREAD

**Issue by raynehe** [Luchixiang/EMDiffuse#4]
Hi! Thanks for your wonderful work!

I'm trying to run EMDiffuse-i on EPFL brain dataset using `vEMDiffuse-i.json` (as shown in Supp. Fig.18). I'm a little confused about how to prepare the data for isotropic reconstruction.

I found `data_root` in `vEMDiffuse-i.json` which is ended with `/train_img`, but the EPFL dataset is simply one `.tif` file. Should I preprocess the data the same way as denoising and super-resolution (using `register.py`)?

Specifically, how can I reproduce the results in Supp. Fig.18 (which parameters should I set)?

Sorry for the bother and looking forward to your reply!

**Comment by Luchixiang** [comment]
Hi. As I mentioned in the README. You should split the 3D ``.tif`` file into 2D tif file: 0.tif, 1.tif, 2.tif, and then run vEMDiffuse-i. The register file is used for the registration of 2D super-resolution and denoise. 

As for the parameter, just use the default parameter and train the model for ~1000 epochs.

**Comment by raynehe** [comment]
Thanks for your help!
