### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by AmingWu** [Luchixiang/EMDiffuse#6]
Dear Authors,
When I train your code, there is an error. Could you give me some advice? Thanks.

![QQ截图20240712151325](https://github.com/user-attachments/assets/97478ac9-63db-47d6-ad68-945b4b314277)

**Comment by Luchixiang** [comment]
I can't reproduce the error. Could you give me more details?

**Comment by AmingWu** [comment]
Dear Authors,
I have trained the code. But there exists a new error:

![QQ截图20240718155535](https://github.com/user-attachments/assets/0aa13429-b8c7-4f5c-bf29-46a9e9603227)

**Comment by Luchixiang** [comment]
You should keep --mean = 1 when training. It is used to generate multiple outputs in the inference stage
