### ISSUE TITLE
how to find self-assessment functionalities

### ISSUE THREAD

**Issue by qxxfd** [Luchixiang/EMDiffuse#7]
Hello, author. In the paper, you mentioned that "EMDiffuse also features self-assessment functionalities on predictions’ reliability." Could you please indicate where this assessment is implemented in the code, and how can I evaluate the reliability of my results?

**Comment by Luchixiang** [comment]
Hi. There is a line to analyze the uncertainty in the line 191 of [model file](https://github.com/Luchixiang/EMDiffuse/blob/master/models/vEMDiffuse_model.py).  The repository doesn't contain the visualization of the uncertainty map.  

In summary,  you can generate multiple outputs and access the standard deviation of the multiple outputs to access the reliability.
